//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Managing_coffee_shop.Module.BusinessObjects.ORMDataModel1
{

    [DefaultProperty("Nam")]
    public partial class Bangluong : DevExpress.Persistent.BaseImpl.BaseObject
    {
        Nhanvien fNhanvienID;
        [Association(@"BangluongReferencesNhanvien")]
        public Nhanvien NhanvienID
        {
            get { return fNhanvienID; }
            set { SetPropertyValue<Nhanvien>(nameof(NhanvienID), ref fNhanvienID, value); }
        }
        long fNam;
        public long Nam
        {
            get { return fNam; }
            set { SetPropertyValue<long>(nameof(Nam), ref fNam, value); }
        }
        long fThang;
        public long Thang
        {
            get { return fThang; }
            set { SetPropertyValue<long>(nameof(Thang), ref fThang, value); }
        }
        long fSogiolam;
        public long Sogiolam
        {
            get { return fSogiolam; }
            set { SetPropertyValue<long>(nameof(Sogiolam), ref fSogiolam, value); }
        }
        decimal fLuong;
        public decimal Luong
        {
            get { return fLuong; }
            set { SetPropertyValue<decimal>(nameof(Luong), ref fLuong, value); }
        }
    }

}
