//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Managing_coffee_shop.Module.BusinessObjects.ORMDataModel1
{

    [DefaultProperty("Sophieu")]

    public partial class Phieunhap : DevExpress.Persistent.BaseImpl.BaseObject
    {
        Nhacungcap fNCCID;
        [Association(@"PhieunhapReferencesNhacungcap")]
        public Nhacungcap NCCID
        {
            get { return fNCCID; }
            set { SetPropertyValue<Nhacungcap>(nameof(NCCID), ref fNCCID, value); }
        }
        Nhanvien fNhanvienID;
        [Association(@"PhieunhapReferencesNhanvien")]
        public Nhanvien NhanvienID
        {
            get { return fNhanvienID; }
            set { SetPropertyValue<Nhanvien>(nameof(NhanvienID), ref fNhanvienID, value); }
        }
        string fSophieu;
        public string Sophieu
        {
            get { return fSophieu; }
            set { SetPropertyValue<string>(nameof(Sophieu), ref fSophieu, value); }
        }
        string fNgay;
        public string Ngay
        {
            get { return fNgay; }
            set { SetPropertyValue<string>(nameof(Ngay), ref fNgay, value); }
        }
    }

}
